[workspace]
resolver = "2"
members = [ "crates/fosr-ebpf","crates/fosr","crates/fosr-lib"]
exclude = ["/dev","/learning","/resources","/public"]
default-members = ["crates/fosr"]

[profile.release]
debug = true
# strip = true
# lto = true
